# Generated by Django 4.0.3 on 2022-03-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(default='nick', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
